name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        build_type: [Debug, Release]
        
    steps:
      - uses: actions/checkout@v4
      - name: Create Build Environment
        run: cmake -E make_directory build

      - name: Configure Project
        working-directory: build
        run: cmake -GNinja $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      - name: Build
        working-directory: build
        run: cmake --build .
      - name: Run Tests
        working-directory: build
        run: ./examples/xalloc_example_allocator_storage

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: ['16']
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{matrix.xcode}}
      - name: Create Build Environment
        run: cmake -E make_directory build
      - name: Install Dependencies
        run: brew install ninja

      - name: Configure Project
        working-directory: build
        run: cmake -GNinja $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Build
        working-directory: build/
        run: cmake --build .
      - name: Run Tests
        working-directory: build/
        run: ./examples/xalloc_example_allocator_storage

  windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch: [Win32, x64]
        build_type: [Debug, Release]
        toolset: ['v142', 'v143', 'ClangCL']

    steps:
      - uses: actions/checkout@v4
      - name: Create Build Environment
        run: cmake -E make_directory build

      - name: Configure Project
        shell: bash
        working-directory: build/
        run: cmake $GITHUB_WORKSPACE -G"Visual Studio 17 2022" -T ${{matrix.toolset}} -A ${{matrix.arch}}
      - name: Build
        working-directory: build/
        run: cmake --build . --config ${{matrix.build_type}} -j 2
      - name: Run Tests
        working-directory: build/examples/
        run: start xalloc_example_allocator_storage.exe
